apiVersion: v1
kind: Service
metadata:
  name: self-checker
  namespace: twcc-util
  labels:
    app: self-checker
spec:
  externalIPs:
    - 172.29.188.60
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app: self-checker